# Generated by Django 3.0.3 on 2020-04-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.CharField(default='', max_length=50),
        ),
    ]
