# Generated by Django 3.0.3 on 2020-04-12 23:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200412_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 23, 50, 43, 622631, tzinfo=utc)),
        ),
    ]
