# Generated by Django 3.0.3 on 2020-04-13 13:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20200412_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='testint',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 13, 45, 26, 175438, tzinfo=utc)),
        ),
    ]
