# Generated by Django 3.0.3 on 2020-04-13 14:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200413_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='dueYear',
        ),
        migrations.AlterField(
            model_name='todo',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 14, 4, 1, 317013, tzinfo=utc)),
        ),
    ]
