# Generated by Django 3.0.3 on 2020-04-15 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_note'),
        ('dashboard', '0013_auto_20200413_1004'),
    ]

    operations = [
    ]
