# Generated by Django 3.0.3 on 2020-04-15 12:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20200413_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 12, 20, 38, 309360, tzinfo=utc)),
        ),
    ]
