# Generated by Django 3.0.3 on 2020-04-15 12:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_merge_20200415_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 12, 55, 41, 235224, tzinfo=utc)),
        ),
    ]
