# Generated by Django 3.0.3 on 2020-04-15 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_event'),
        ('dashboard', '0015_auto_20200415_0845'),
    ]

    operations = [
    ]
