# Generated by Django 3.0.3 on 2020-04-15 17:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20200415_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 17, 50, 46, 471079, tzinfo=utc)),
        ),
    ]
