# Generated by Django 3.0.3 on 2020-04-15 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20200415_1352'),
        ('dashboard', '0017_merge_20200415_1734'),
    ]

    operations = [
    ]
