# Generated by Django 3.0.3 on 2020-04-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20200416_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city_location',
            field=models.CharField(blank=True, default='Charlottesville', max_length=30),
        ),
    ]
