# Generated by Django 3.0.3 on 2020-04-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20200416_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city_location',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
