# Generated by Django 3.0.3 on 2020-04-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20200416_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state_location',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
