# Generated by Django 3.0.3 on 2020-04-26 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_todo_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='current',
        ),
        migrations.AlterField(
            model_name='todo',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 17, 46, 37, 900802)),
        ),
    ]
