# Generated by Django 3.0.3 on 2020-04-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20200426_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='current',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
