# Generated by Django 3.0.3 on 2020-04-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_todo_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='current',
            field=models.DateTimeField(blank=True),
        ),
    ]
