# Generated by Django 3.0.3 on 2020-04-26 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_auto_20200426_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='current',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='is_active',
        ),
    ]
