# Generated by Django 3.0.3 on 2020-04-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_todo_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='current',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
