# Generated by Django 3.0.3 on 2020-04-27 01:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_auto_20200426_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='current',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 1, 26, 46, 338321, tzinfo=utc)),
        ),
    ]
