# Generated by Django 3.0.3 on 2020-04-27 01:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_auto_20200426_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='current',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
