# Generated by Django 3.0.3 on 2020-04-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_auto_20200427_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
